# This file is machine-generated - editing it directly is not advised

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[TensorAlgebra]]
deps = ["LinearAlgebra"]
path = "../TensorAlgebra"
uuid = "84c0c5c2-3611-43dd-b4f2-3e690a28d148"
version = "0.1.0"
